services:
  db:
    image: postgres:15-alpine
    container_name: pingpay_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pingpay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ocr:
    build: ./ocr
    container_name: pingpay_ocr
    restart: unless-stopped
    ports:
      - "8866:8866"

volumes:
  postgres_data:
